name: hvac_dashboard
description: Responsive HVAC/BMS dashboard UI built with Flutter for Three Energy Control (3EC).
publish_to: "none"
version: 1.0.0+20260502
homepage: https://github.com/3EC-DEVELOPER/flutter_projects-3EC-hvac_dashboard
repository: https://github.com/3EC-DEVELOPER/flutter_projects-3EC-hvac_dashboard

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
